/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/UYTXxfnpEFF
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Switch } from "@/components/ui/switch"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"

export function perps-portfolio() {
  return (
    <Card className="w-full max-w-4xl">
      <CardHeader className="flex items-center justify-between">
        <CardTitle>Perpetual Futures Portfolio</CardTitle>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="ghost" size="icon">
              <SettingsIcon className="h-5 w-5" />
              <span className="sr-only">Portfolio Settings</span>
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuItem>
              <div className="flex items-center justify-between">
                <span>Hide Leverage</span>
                <Switch />
              </div>
            </DropdownMenuItem>
            <DropdownMenuItem>
              <div className="flex items-center justify-between">
                <span>Hide Liquidation Price</span>
                <Switch />
              </div>
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </CardHeader>
      <CardContent className="grid gap-6">
        <div className="grid md:grid-cols-2 gap-6">
          <Card>
            <CardHeader>
              <CardTitle>Open Positions</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col gap-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <div className="w-3 h-3 rounded-full bg-green-500" />
                    <span>Long</span>
                  </div>
                  <div className="text-2xl font-bold">$12,345</div>
                </div>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <div className="w-3 h-3 rounded-full bg-red-500" />
                    <span>Short</span>
                  </div>
                  <div className="text-2xl font-bold">$6,789</div>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Performance</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col gap-4">
                <div className="flex items-center justify-between">
                  <span>ROI</span>
                  <div className="text-2xl font-bold text-green-500">+12.5%</div>
                </div>
                <div className="flex items-center justify-between">
                  <span>Realized P/L</span>
                  <div className="text-2xl font-bold text-green-500">$1,234</div>
                </div>
                <div className="flex items-center justify-between">
                  <span>Avg. Leverage</span>
                  <div className="text-2xl font-bold">10x</div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
        <div>
          <div className="flex items-center justify-between mb-4">
            <CardTitle>Active Trades</CardTitle>
            <div className="flex items-center gap-2 text-muted-foreground">
              <CalendarClockIcon className="h-5 w-5" />
              <span>Last 30 days</span>
            </div>
          </div>
          <div className="border shadow-sm rounded-lg overflow-hidden">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Pair</TableHead>
                  <TableHead>Type</TableHead>
                  <TableHead>Entry</TableHead>
                  <TableHead>Size</TableHead>
                  <TableHead>Leverage</TableHead>
                  <TableHead>Liq. Price</TableHead>
                  <TableHead>PnL</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell>BTC-PERP</TableCell>
                  <TableCell>Long</TableCell>
                  <TableCell>$50,000</TableCell>
                  <TableCell>0.5 BTC</TableCell>
                  <TableCell>10x</TableCell>
                  <TableCell>$45,000</TableCell>
                  <TableCell className="text-green-500">+$1,234</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>ETH-PERP</TableCell>
                  <TableCell>Short</TableCell>
                  <TableCell>$2,500</TableCell>
                  <TableCell>2 ETH</TableCell>
                  <TableCell>5x</TableCell>
                  <TableCell>$2,800</TableCell>
                  <TableCell className="text-red-500">-$500</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>SOL-PERP</TableCell>
                  <TableCell>Long</TableCell>
                  <TableCell>$100</TableCell>
                  <TableCell>50 SOL</TableCell>
                  <TableCell>20x</TableCell>
                  <TableCell>$90</TableCell>
                  <TableCell className="text-green-500">+$250</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </div>
        </div>
        <div className="grid md:grid-cols-2 gap-6">
          <Card>
            <CardHeader>
              <CardTitle>Funding Rate</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col gap-4">
                <div className="flex items-center justify-between">
                  <span>BTC-PERP</span>
                  <div className="text-2xl font-bold text-green-500">+0.01%</div>
                </div>
                <div className="flex items-center justify-between">
                  <span>ETH-PERP</span>
                  <div className="text-2xl font-bold text-red-500">-0.02%</div>
                </div>
                <div className="flex items-center justify-between">
                  <span>SOL-PERP</span>
                  <div className="text-2xl font-bold text-green-500">+0.005%</div>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Funding Impact</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col gap-4">
                <div className="flex items-center justify-between">
                  <span>BTC-PERP</span>
                  <div className="text-2xl font-bold text-green-500">+$50</div>
                </div>
                <div className="flex items-center justify-between">
                  <span>ETH-PERP</span>
                  <div className="text-2xl font-bold text-red-500">-$30</div>
                </div>
                <div className="flex items-center justify-between">
                  <span>SOL-PERP</span>
                  <div className="text-2xl font-bold text-green-500">+$10</div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </CardContent>
    </Card>
  )
}

function CalendarClockIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 7.5V6a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h3.5" />
      <path d="M16 2v4" />
      <path d="M8 2v4" />
      <path d="M3 10h5" />
      <path d="M17.5 17.5 16 16.3V14" />
      <circle cx="16" cy="16" r="6" />
    </svg>
  )
}


function SettingsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}
